server:
  port: 9094

#eureka:
#  client:
#    service-url:
#      defaultZone:  http://localhost:8761/eureka/
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#
#
spring:
  profiles:
    active: dev
  application:
    name:  ORDER-SERVICE
#  data:
#    mongodb:
#      url:  mongodb/mongodb-community-server
#      host:  localhost
#      port:  27017
#      database:  test-mongodb
#      repositories:
#        enabled:  true
#  profiles:
#    active: dev